def access_key=""
def secret_key=""
def data = ""
def gcp_auth_file = "/tmp/cred.json"
pipeline {
  agent any

  parameters {
        string(name: 'app_name', defaultValue: 'test1', description: 'Provide Application name to be deploy') 
		choice(name: 'app_environment', choices: ['dev', 'qa', 'pre-prod', 'prod'], description: 'Specify environment' )
		choice(name: 'gcp_project', choices: ['sagar-trial-account'], description: 'Specify gcp project' )
		choice(name: 'gcp_region', choices: ['europe-west1'], description: 'Specify gcp region' )
		choice(name: 'machine_type', choices: ['f1-micro'], description: 'Specify instance type' )
    }
  stages {
   stage('Preparations') {
      steps {
	script {
		withCredentials ([usernamePassword(credentialsId: 'aws_credentails', usernameVariable: 'aws_access_key', passwordVariable: 'aws_secret_key')]) {
		   access_key = aws_access_key
		   secret_key = aws_secret_key
		}
	}
	dir('gcp') {
		script {
			data = "gcp_project=\"${gcp_project}\"\n"
			data = data + "gcp_auth_file=\"${gcp_auth_file}\"\n"
			data = data + "app_name=\"${app_name}\"\n"
			data = data + "app_environment=\"${app_environment}\"\n"
			data = data + "gcp_region=\"${gcp_region}\"\n"
			data = data + "machine_type=\"${machine_type}\"\n"
		}
	writeFile file: "${BUILD_ID}_terraform.tfvars", text: data
	sh "cat ${BUILD_ID}_terraform.tfvars"
      	  }
      }
    }
    stage('Terraform Init') {
      steps {
	dir('gcp') {  
		sh "terraform init -backend-config=\"conn_str=postgres://jenkins:jenkins@localhost/terraformstate?sslmode=disable\" -input=false"
		//sh "terraform init  -input=false -backend-config=\"bucket=jenkins\" -backend-config=\"access_key=${access_key}\" -backend-config=\"secret_key=${secret_key}\" -backend-config=\"region=${aws_region}\" -backend-config=\"key=tf-state/${BUILD_ID}_terraform.tfstate\""
		sh "terraform workspace new ${BUILD_ID}-state"
		sh "terraform workspace select  ${BUILD_ID}-state"
		sh "terraform workspace show"
		sh "terraform state pull"
	  }
       }
    }
    stage('Terraform Plan') {
      steps {
	dir('gcp') {   
        	sh "terraform plan -out=tfplan -var-file=${BUILD_ID}_terraform.tfvars"
        	sh "terraform show -no-color tfplan > ${BUILD_ID}_tfplan.txt"
	}
      }
    }
   stage('Terraform Apply') {
      steps {
	dir('gcp') {   
        	sh "terraform apply -input=false -auto-approve tfplan"
		sh "terraform output"
	}
      }
    }
  stage('Terraform Destroy Approval') {
	   steps {
		   dir('gcp') {  
            script {
                def plan = readFile "${BUILD_ID}_tfplan.txt"
                input message: "Do you want to destroy the plan?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
            }
		   }
        }
    }
stage('Terraform Destroy') {
      steps {
	dir('gcp') {   
		sh "terraform workspace select  ${BUILD_ID}-state"
        	sh "terraform destroy -input=false -auto-approve -var-file=${BUILD_ID}_terraform.tfvars"
	}
      }
    }
  }
  post {
        always {
		dir('aws') { 
            archiveArtifacts artifacts: "${BUILD_ID}_tfplan.txt"
			//cleanWs()
		}
        }
    }
}
